Update README.md
at-internship/at-sso-ui pull request #17
Opened 2020-12-14 15:20 UTC by LuisAPerez224

2020-12-14 16:45 UTC, irvingesp2190 approved these changes

2020-12-14 16:49 UTC, at-internship requested changes

2020-12-14 16:49 UTC, at-internship commented on README.md
> +at-sso-ui app, is one of the 3 projects of this internship program, which is in charge of managing users, based on SCRUM methodology.
is not based on  SCRUM methodology.

2020-12-14 16:49 UTC, at-internship commented on README.md
> +### Code Coverage
**Code Coverage**
- $ npm install nock --save-dev
- $ npm run coverage

2020-12-17 22:51 UTC, at-internship approved these changes
Approved

2020-12-17 23:03 UTC, merged