Implementation and structure of the sso project
at-internship/at-sso-ui pull request #4
Opened 2020-10-02 18:09 UTC by Normaillescas29

2020-10-02 18:16 UTC, irvingesp2190 approved these changes

2020-10-02 18:22 UTC, irvingesp2190 approved these changes

2020-10-02 20:17 UTC, Normaillescas29 reviewed
Done

2020-10-02 20:30 UTC, pinto1997 approved these changes

2020-10-02 20:31 UTC, irvingesp2190 approved these changes

2020-10-04 19:13 UTC, Ignacio-jipl97 commented
Add routes

2020-10-05 14:12 UTC, at-internship commented on src/routes/at-sso.routes.js
> +router.post('/user',addUser);
router.post('/user', addUser);

2020-10-05 14:13 UTC, at-internship commented on src/controllers/admin.controller.js
> +adminCtrl.renderUserForm = (req,res) => {
adminCtrl.renderUserForm = (req, res) =>

2020-10-05 14:15 UTC, at-internship requested changes
Please, take a look at the comments

2020-10-05 15:32 UTC, closed without merging